name: ateba_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dio: ^5.3.2
  retrofit: ^4.0.1
  logger: ^2.0.1
  json_serializable: ^6.7.1
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.1
  easy_localization: ^3.0.2
  go_router: ^11.0.0
  theme_provider: ^0.6.0
  flutter_svg: ^1.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.2
  shimmer: ^3.0.0
  dio_cookie_manager: ^2.0.0
  shamsi_date: ^1.0.1
  video_player: ^2.7.0
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  pinput: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  retrofit_generator: ^7.0.8

flutter:

  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/yekan-bakh/YekanBakh-Bold.ttf
          weight: 900
        - asset: assets/fonts/yekan-bakh/YekanBakh-Bold.ttf
          weight: 800
        - asset: assets/fonts/yekan-bakh/YekanBakh-Bold.ttf
          weight: 700
        - asset: assets/fonts/yekan-bakh/YekanBakh-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/yekan-bakh/YekanBakh-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/yekan-bakh/YekanBakh-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/yekan-bakh/YekanBakh-Regular.ttf
          weight: 300
        - asset: assets/fonts/yekan-bakh/YekanBakh-Regular.ttf
          weight: 200
        - asset: assets/fonts/yekan-bakh/YekanBakh-Regular.ttf
          weight: 100