name: ateba_app
description: A new Flutter project.

publish_to: 'none' 

version: 2.1.15+19

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  dio: ^5.3.2
  retrofit: ^4.0.1
  logger: ^2.0.1
  json_serializable: ^6.7.1
  cached_network_image: ^3.2.3
  json_annotation: ^4.8.1
  easy_localization: ^3.0.2
  go_router: ^11.0.0
  theme_provider: ^0.6.0
  flutter_svg: ^1.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.2
  shimmer: ^3.0.0
  dio_cookie_manager: ^2.0.0
  shamsi_date: ^1.0.1
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  pinput: ^3.0.1
  url_launcher: ^6.1.14
  video_player: ^2.7.2
  lazy_load_scrollview: ^1.3.0
  path_provider: ^2.1.1
  intl: ^0.18.0
  flutter_animated_dialog: ^2.0.1
  flutter_keyboard_visibility: ^5.4.1
  bot_toast: ^4.1.3
  percent_indicator: ^4.2.3
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.1.0
  styled_text: ^8.1.0
  super_tooltip: ^2.0.7
  otp_autofill: ^3.0.0
  photo_view: ^0.14.0
  audioplayers: ^5.2.0
  flutter_pdfview: ^1.3.2
  flutter_local_notifications: ^9.9.1
  firebase_core: ^2.19.0
  firebase_messaging: ^14.2.2
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1
  retrofit_generator: ^7.0.8
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  adaptive_icon_background: "assets/appIcon/bg_logo.png"
  adaptive_icon_foreground: "assets/appIcon/fg_logo.png"
  image_path_android: "assets/appIcon/main_logo.png"
  image_path: "assets/appIcon/main_logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/
    - assets/appIcon/

  fonts:
    - family: YekanBakh
      fonts:
        - asset: assets/fonts/yekan-bakh/YekanBakh-Bold.ttf
          weight: 900
        - asset: assets/fonts/yekan-bakh/YekanBakh-Bold.ttf
          weight: 800
        - asset: assets/fonts/yekan-bakh/YekanBakh-Bold.ttf
          weight: 700
        - asset: assets/fonts/yekan-bakh/YekanBakh-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/yekan-bakh/YekanBakh-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/yekan-bakh/YekanBakh-SemiBold.ttf
          weight: 400
        - asset: assets/fonts/yekan-bakh/YekanBakh-Regular.ttf
          weight: 300
        - asset: assets/fonts/yekan-bakh/YekanBakh-Regular.ttf
          weight: 200
        - asset: assets/fonts/yekan-bakh/YekanBakh-Regular.ttf
          weight: 100