// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS7hNsVp9PkwSdEthYGBfOjwtqkBAnNmU',
    appId: '1:875233357360:web:5bc2588ec9f5fb71cc87f5',
    messagingSenderId: '875233357360',
    projectId: 'ateba-8aaf2',
    authDomain: 'ateba-8aaf2.firebaseapp.com',
    storageBucket: 'ateba-8aaf2.appspot.com',
    measurementId: 'G-LHWESJK3Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7D5IYLAUXpdRmk_sGYgZ1oTzY4Jrjq1U',
    appId: '1:875233357360:android:f37c28d5e4538597cc87f5',
    messagingSenderId: '875233357360',
    projectId: 'ateba-8aaf2',
    storageBucket: 'ateba-8aaf2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4c5DwMqkFi9YWg4t2W0kdI7OkFXOFjFQ',
    appId: '1:875233357360:ios:ed7c368307526c12cc87f5',
    messagingSenderId: '875233357360',
    projectId: 'ateba-8aaf2',
    storageBucket: 'ateba-8aaf2.appspot.com',
    iosBundleId: 'com.example.atebaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4c5DwMqkFi9YWg4t2W0kdI7OkFXOFjFQ',
    appId: '1:875233357360:ios:c5e96fd2a62d6c17cc87f5',
    messagingSenderId: '875233357360',
    projectId: 'ateba-8aaf2',
    storageBucket: 'ateba-8aaf2.appspot.com',
    iosBundleId: 'com.example.atebaApp.RunnerTests',
  );
}
